FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /loc-history ./cmd/loc-history

FROM alpine:3.19
RUN apk --no-cache add ca-certificates tzdata
COPY --from=builder /loc-history /loc-history
EXPOSE 8081 50051
ENTRYPOINT ["/loc-history"]
