// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: pkg/proto/location.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveLocationRequest) Reset() {
	*x = SaveLocationRequest{}
	mi := &file_pkg_proto_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveLocationRequest) ProtoMessage() {}

func (x *SaveLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveLocationRequest.ProtoReflect.Descriptor instead.
func (*SaveLocationRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_location_proto_rawDescGZIP(), []int{0}
}

func (x *SaveLocationRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SaveLocationRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *SaveLocationRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *SaveLocationRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type SaveLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveLocationResponse) Reset() {
	*x = SaveLocationResponse{}
	mi := &file_pkg_proto_location_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveLocationResponse) ProtoMessage() {}

func (x *SaveLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_location_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveLocationResponse.ProtoReflect.Descriptor instead.
func (*SaveLocationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_location_proto_rawDescGZIP(), []int{1}
}

func (x *SaveLocationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_pkg_proto_location_proto protoreflect.FileDescriptor

const file_pkg_proto_location_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/proto/location.proto\x12\blocation\"\x89\x01\n" +
	"\x13SaveLocationRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\"0\n" +
	"\x14SaveLocationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2g\n" +
	"\x16LocationHistoryService\x12M\n" +
	"\fSaveLocation\x12\x1d.location.SaveLocationRequest\x1a\x1e.location.SaveLocationResponseB9Z7github.com/training/GOLANG_FOR_STUDENTS/pkg/proto;protob\x06proto3"

var (
	file_pkg_proto_location_proto_rawDescOnce sync.Once
	file_pkg_proto_location_proto_rawDescData []byte
)

func file_pkg_proto_location_proto_rawDescGZIP() []byte {
	file_pkg_proto_location_proto_rawDescOnce.Do(func() {
		file_pkg_proto_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_location_proto_rawDesc), len(file_pkg_proto_location_proto_rawDesc)))
	})
	return file_pkg_proto_location_proto_rawDescData
}

var file_pkg_proto_location_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_location_proto_goTypes = []any{
	(*SaveLocationRequest)(nil),  // 0: location.SaveLocationRequest
	(*SaveLocationResponse)(nil), // 1: location.SaveLocationResponse
}
var file_pkg_proto_location_proto_depIdxs = []int32{
	0, // 0: location.LocationHistoryService.SaveLocation:input_type -> location.SaveLocationRequest
	1, // 1: location.LocationHistoryService.SaveLocation:output_type -> location.SaveLocationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_location_proto_init() }
func file_pkg_proto_location_proto_init() {
	if File_pkg_proto_location_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_location_proto_rawDesc), len(file_pkg_proto_location_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_location_proto_goTypes,
		DependencyIndexes: file_pkg_proto_location_proto_depIdxs,
		MessageInfos:      file_pkg_proto_location_proto_msgTypes,
	}.Build()
	File_pkg_proto_location_proto = out.File
	file_pkg_proto_location_proto_goTypes = nil
	file_pkg_proto_location_proto_depIdxs = nil
}
