// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: pkg/proto/location.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LocationHistoryService_SaveLocation_FullMethodName = "/location.LocationHistoryService/SaveLocation"
)

// LocationHistoryServiceClient is the client API for LocationHistoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LocationHistoryServiceClient interface {
	SaveLocation(ctx context.Context, in *SaveLocationRequest, opts ...grpc.CallOption) (*SaveLocationResponse, error)
}

type locationHistoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLocationHistoryServiceClient(cc grpc.ClientConnInterface) LocationHistoryServiceClient {
	return &locationHistoryServiceClient{cc}
}

func (c *locationHistoryServiceClient) SaveLocation(ctx context.Context, in *SaveLocationRequest, opts ...grpc.CallOption) (*SaveLocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveLocationResponse)
	err := c.cc.Invoke(ctx, LocationHistoryService_SaveLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocationHistoryServiceServer is the server API for LocationHistoryService service.
// All implementations must embed UnimplementedLocationHistoryServiceServer
// for forward compatibility.
type LocationHistoryServiceServer interface {
	SaveLocation(context.Context, *SaveLocationRequest) (*SaveLocationResponse, error)
	mustEmbedUnimplementedLocationHistoryServiceServer()
}

// UnimplementedLocationHistoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLocationHistoryServiceServer struct{}

func (UnimplementedLocationHistoryServiceServer) SaveLocation(context.Context, *SaveLocationRequest) (*SaveLocationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveLocation not implemented")
}
func (UnimplementedLocationHistoryServiceServer) mustEmbedUnimplementedLocationHistoryServiceServer() {
}
func (UnimplementedLocationHistoryServiceServer) testEmbeddedByValue() {}

// UnsafeLocationHistoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LocationHistoryServiceServer will
// result in compilation errors.
type UnsafeLocationHistoryServiceServer interface {
	mustEmbedUnimplementedLocationHistoryServiceServer()
}

func RegisterLocationHistoryServiceServer(s grpc.ServiceRegistrar, srv LocationHistoryServiceServer) {
	// If the following call panics, it indicates UnimplementedLocationHistoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LocationHistoryService_ServiceDesc, srv)
}

func _LocationHistoryService_SaveLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationHistoryServiceServer).SaveLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationHistoryService_SaveLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationHistoryServiceServer).SaveLocation(ctx, req.(*SaveLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LocationHistoryService_ServiceDesc is the grpc.ServiceDesc for LocationHistoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LocationHistoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "location.LocationHistoryService",
	HandlerType: (*LocationHistoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveLocation",
			Handler:    _LocationHistoryService_SaveLocation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/location.proto",
}
